apiVersion: v1
kind: ConfigMap
metadata:
    name: nginx-config
data:
    APP_ENV: "development"
    APP_NAME: "namhoang-demo"
---
apiVersion: v1
kind: Secret
metadata:
    name: nginx-secret
type: Opaque
data:
    DB_PASSWORD: cGFzc3dvcmQxMjM=
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-with-config
spec:
    replicas: 1
    selector:
        matchLabels:
            app: nginx-config
    template:
        metadata:
            labels:
                app: nginx-config
        spec:
            containers:
                - name: nginx
                  image: nginx:1.25
                  envFrom:
                      - configMapRef:
                            name: nginx-config
                  env:
                      - name: DB_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: nginx-secret
                                key: DB_PASSWORD
