# ServiceAccount cho developer
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-developer
  namespace: app-dev
---
# ServiceAccount cho sre
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-sre
  namespace: kube-system
---
# ServiceAccount cho viewer
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-viewer
  namespace: default
