# ── K8s Bootstrap Verification (null provider) ──────────────────────────────
# Provider: hashicorp/null (provider #3)
#
# Why null + remote-exec instead of hashicorp/kubernetes provider?
# The kubernetes provider requires EC2 IP + cluster token at plan time,
# but the EC2 doesn't exist yet — a chicken-and-egg problem.
#
# null_resource + remote-exec solves this cleanly:
#   - Runs AFTER EC2 is created (depends_on)
#   - SSHes in using the TLS key generated by provider #2 (tls)
#   - Polls until bootstrap script completes (/tmp/bootstrap_done)
#   - Verifies K8s cluster nodes and app pods are healthy
#   - Fails loudly if anything went wrong — not silently
#
# This enables TRUE 1-click: single terraform apply, no manual steps.

resource "null_resource" "verify_k8s" {
  # Re-trigger if EC2 is recreated or user_data changes
  triggers = {
    instance_id   = aws_instance.k8s_host.id
    user_data_sha = filesha256("${path.module}/scripts/user_data.sh")
  }

  depends_on = [time_sleep.wait_for_ssh]

  connection {
    type        = "ssh"
    host        = aws_instance.k8s_host.public_ip
    user        = "ubuntu"
    private_key = tls_private_key.ssh.private_key_pem
    timeout     = "15m"
  }

  # Step 1: Poll until bootstrap script finishes (timeout 15 min)
  provisioner "remote-exec" {
    inline = [
      "echo '============================================'",
      "echo '[Terraform] Waiting for EC2 bootstrap...'",
      "echo '============================================'",
      "timeout 900 bash -c 'until [ -f /tmp/bootstrap_done ]; do echo \"[$(date +%T)] Waiting for bootstrap...\"; sleep 15; done'",
      "echo '[Terraform] Bootstrap complete! Status:'",
      "cat /tmp/bootstrap_status 2>/dev/null || echo 'unknown'",
    ]
  }

  # Step 2: Verify K8s cluster health
  provisioner "remote-exec" {
    inline = [
      "echo '============================================'",
      "echo '[Terraform] Verifying K8s cluster...'",
      "echo '============================================'",
      "export KUBECONFIG=/home/ubuntu/.kube/config",
      "kubectl get nodes -o wide",
      "kubectl get pods --all-namespaces",
    ]
  }

  # Step 3: Verify the hello-xbrain app is running
  provisioner "remote-exec" {
    inline = [
      "echo '============================================'",
      "echo '[Terraform] Verifying hello-xbrain app...'",
      "echo '============================================'",
      "export KUBECONFIG=/home/ubuntu/.kube/config",
      "kubectl get pods -n hello-xbrain -o wide",
      "kubectl get svc -n hello-xbrain",
      "kubectl wait --for=condition=ready pod -l app=hello-xbrain -n hello-xbrain --timeout=120s",
      "echo ''",
      "echo '[Terraform] App is RUNNING on Kubernetes!'",
      "echo '[Terraform] NodePort: 30080'",
      "echo '[Terraform] ALB will route traffic to this port'",
      "echo '============================================'",
    ]
  }
}
