# SecretStore — cấu hình kết nối tới AWS Secrets Manager
# Một lần cấu hình, nhiều ExternalSecret có thể dùng chung
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
    name: aws-secretsmanager
    namespace: app-dev
spec:
    provider:
        aws:
            service: SecretsManager
            region: ap-southeast-1
            auth:
                secretRef:
                    # ESO đọc AWS credentials từ K8s Secret này
                    accessKeyIDSecretRef:
                        name: aws-credentials
                        key: access-key-id
                    secretAccessKeySecretRef:
                        name: aws-credentials
                        key: secret-access-key
