# ExternalSecret — K8s resource khai báo "lấy secret từ AWS Secrets Manager"
# ESO sẽ đọc file này, gọi AWS API, và tạo K8s Secret tương ứng
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: demo-secret
    namespace: app-dev
spec:
    # refreshInterval: tần suất ESO tự động kiểm tra AWS để rotate secret
    refreshInterval: 1m

    secretStoreRef:
        name: aws-secretsmanager # tên SecretStore đã cấu hình AWS credentials
        kind: SecretStore

    target:
        name: demo-k8s-secret # tên K8s Secret sẽ được tạo ra
        creationPolicy: Owner # ESO quản lý lifecycle của Secret này

    data:
        - secretKey: db-password # key trong K8s Secret
          remoteRef:
              key: w10/demo/db-password # tên secret trong AWS Secrets Manager
              version: AWSCURRENT # lấy version hiện tại
